### PR TITLE
Fix pattern decorator, because the UI expects 'value' instead of 'regexp...

### PR DESCRIPTION
**Pull request by gzsombor**
...'

### CODE REVIEW

**Comment by marcelstoer** [comment]
Thanks. Quite embarrassing there's no unit test for this. I just wrote one before I merged your PR.

**Comment by gzsombor** [comment]
Thanks !

**Comment by surendrakashyap** [comment]
when we do expect this to be release? or is there a work around for @pattern value

**Comment by marcelstoer** [comment]
You're too late ;-) Was released yesterday: https://github.com/netceteragroup/valdr-bean-validation/releases

**Pull request merged**
