### PR TITLE
Added Java 8 compatibility.

### PR DESCRIPTION
**Pull request by Arzie**
Some minor change to get it working with Java 8.

### CODE REVIEW

**Comment by Arzie** [comment]
@marcelstoer Can you have a look at this PR? Thanks!

**Comment by marcelstoer** [comment]
Sorry, I totally forgot about this PR. Thanks for the reminder. I _can_ (and should) add Java 8 compatibility but there are three issues with this PR:
- whitespace
- import ordering
- JVM target version must remain at 1.7 because I don't want to drop Java 7 support yet

**Comment by Arzie** [comment]
OK, I'll try to fix those first. Thanks for your quick reply!

**Comment by Arzie** [comment]
There we go ;-). Did I fix the whitespace issue (I'm not sure where the problem was)?

**Comment by Arzie** [comment]
OK, so either the buildhive build passes (which runs on Java 1.7), or the Travis build passes (which runs on 1.8). I'll apply the test fixes once more, so the build will pass on Java 1.8 (which we're targeting anyway).

**Comment by Arzie** [comment]
@marcelstoer I think I fixed the issues, can you have another look? 

The tests still give some trouble, maybe they should be made more stable somehow? They're dependent on the exact form of the JSON, which seems to change from build to build.

**Comment by marcelstoer** [comment]
I'm taking a look now but you certainly can't run a Maven targeting Java 8 with a Java 7 compiler. For Travis this information is in `.travis.yml` for BuildHive and drone.io it's in the build job configuration.

**Comment by Arzie** [comment]
Well, the pom.xml now targets 1.7 again, so that should work fine. I updated the Travis config file to make it run on JDK 8, but I can't change the BuildHive config.

**Comment by marcelstoer** [comment]
@Arzie Given that 
- any Java 7 code will run on a JVM 8
- you [cannot](http://stackoverflow.com/q/16143684/131929) compile Java 8 code to run on a JVM 7 (i.e. `javac Test -source 1.8 -target 1.7` doesn't work)
- you essentially just updated `reflections.version` from 0.9.8 to 0.9.9

I was wondering what you really were trying to accomplish. Is reflections 0.9.9 required if you want to run on a JVM 8? I didn't find any such reference in their documentation.

**Comment by Arzie** [comment]
The main change is indeed the version of the reflections dependency. If I remember correctly this was the issue we had with it:
https://code.google.com/p/reflections/issues/detail?id=169

So if you're trying to analyse Java 8 sources with valdr-bean-validation, you're not getting the results you want.

**Comment by marcelstoer** [comment]
Ahh, thanks for the link to that issue. I only checked their issues on GitHub.

**Comment by Arzie** [comment]
Thanks Marcel!

**Comment by marcelstoer** [comment]
I just released 1.1.1, should show up in Maven Central shortly.

**Comment by Arzie** [comment]
Cool, I'll start using it right away ;-).

**Pull request merged**
