### PR TITLE
Add support for selecting simple (default) or full type names

### PR DESCRIPTION
**Pull request by Arzie**

### CODE REVIEW

**Comment by marcelstoer** [comment]
@philippd what's your take on this? We've been using the class' simple name on purpose because we want to "encourage" people to use unique names for their entities/model classes. One shouldn't have two `Person` model classes in two different packages.

**Comment by Arzie** [comment]
@marcelstoer How about two `Name` classes in different packages? That's our use case at the moment ;-).

**Comment by philippd** [comment]
This should work fine. The only thing to keep in mind is to always use the fully qualified class name in the valdr-type directive when this option is enabled.

**Comment by marcelstoer** [comment]
> This should work fine.

Yes, it _will_ work. I'm just not sure whether we should offer that option at all? IIRC we've been discussing this before during the initial implementation. It's irrelevant whether your model class is a `Person` or a `Name` (even though it's semantically more generic) it's IMO still bad practice.

My point essentially is about how restrictive the project should be in enforcing what _we_ consider good or bad practice.

**Comment by philippd** [comment]
Yes we discussed it back then and decided to use the simple name to encourage best practices and keep the names in the markup short.

IMO it's fine to add the option as long as the default is to use the simple name. This way we still encourage to use what we consider good practice, but also support cases where someone might not be able to avoid having two classes with the same name (3rd party code).

**Comment by Arzie** [comment]
I could add a comment to make it explicit that the simple name is the suggested usage, would that help?

**Pull request merged**
